# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vyrus/experimental-network/Test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vyrus/experimental-network/Test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vyrus/experimental-network/Test/CMakeFiles /home/vyrus/experimental-network/Test/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vyrus/experimental-network/Test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named floodbot

# Build rule for target.
floodbot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 floodbot
.PHONY : floodbot

# fast build rule for target.
floodbot/fast:
	$(MAKE) -f CMakeFiles/floodbot.dir/build.make CMakeFiles/floodbot.dir/build
.PHONY : floodbot/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/floodbot.dir/build.make CMakeFiles/floodbot.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/floodbot.dir/build.make CMakeFiles/floodbot.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/floodbot.dir/build.make CMakeFiles/floodbot.dir/main.cpp.s
.PHONY : main.cpp.s

opcode.o: opcode.cpp.o
.PHONY : opcode.o

# target to build an object file
opcode.cpp.o:
	$(MAKE) -f CMakeFiles/floodbot.dir/build.make CMakeFiles/floodbot.dir/opcode.cpp.o
.PHONY : opcode.cpp.o

opcode.i: opcode.cpp.i
.PHONY : opcode.i

# target to preprocess a source file
opcode.cpp.i:
	$(MAKE) -f CMakeFiles/floodbot.dir/build.make CMakeFiles/floodbot.dir/opcode.cpp.i
.PHONY : opcode.cpp.i

opcode.s: opcode.cpp.s
.PHONY : opcode.s

# target to generate assembly for a file
opcode.cpp.s:
	$(MAKE) -f CMakeFiles/floodbot.dir/build.make CMakeFiles/floodbot.dir/opcode.cpp.s
.PHONY : opcode.cpp.s

packet.o: packet.cpp.o
.PHONY : packet.o

# target to build an object file
packet.cpp.o:
	$(MAKE) -f CMakeFiles/floodbot.dir/build.make CMakeFiles/floodbot.dir/packet.cpp.o
.PHONY : packet.cpp.o

packet.i: packet.cpp.i
.PHONY : packet.i

# target to preprocess a source file
packet.cpp.i:
	$(MAKE) -f CMakeFiles/floodbot.dir/build.make CMakeFiles/floodbot.dir/packet.cpp.i
.PHONY : packet.cpp.i

packet.s: packet.cpp.s
.PHONY : packet.s

# target to generate assembly for a file
packet.cpp.s:
	$(MAKE) -f CMakeFiles/floodbot.dir/build.make CMakeFiles/floodbot.dir/packet.cpp.s
.PHONY : packet.cpp.s

udp_connection.o: udp_connection.cpp.o
.PHONY : udp_connection.o

# target to build an object file
udp_connection.cpp.o:
	$(MAKE) -f CMakeFiles/floodbot.dir/build.make CMakeFiles/floodbot.dir/udp_connection.cpp.o
.PHONY : udp_connection.cpp.o

udp_connection.i: udp_connection.cpp.i
.PHONY : udp_connection.i

# target to preprocess a source file
udp_connection.cpp.i:
	$(MAKE) -f CMakeFiles/floodbot.dir/build.make CMakeFiles/floodbot.dir/udp_connection.cpp.i
.PHONY : udp_connection.cpp.i

udp_connection.s: udp_connection.cpp.s
.PHONY : udp_connection.s

# target to generate assembly for a file
udp_connection.cpp.s:
	$(MAKE) -f CMakeFiles/floodbot.dir/build.make CMakeFiles/floodbot.dir/udp_connection.cpp.s
.PHONY : udp_connection.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... floodbot"
	@echo "... rebuild_cache"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... opcode.o"
	@echo "... opcode.i"
	@echo "... opcode.s"
	@echo "... packet.o"
	@echo "... packet.i"
	@echo "... packet.s"
	@echo "... udp_connection.o"
	@echo "... udp_connection.i"
	@echo "... udp_connection.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

